//{{NO_DEPENDENCIES}}
// RuliManager.rc 에서 사용
//
#define IDD_RULIMANAGER_DIALOG     102
#define IDR_MAINFRAME               128
#define IDD_ACTORS                  130
#define IDD_ACTOR_PICK              131
#define IDD_INPUT                   132
#define IDD_NAMELIST                133
#define IDD_BULK_NAMES              138
#define IDD_TEXT_INFO               139
#define IDD_NAME_PICK               134
#define IDB_FLAGS                   135
#define IDD_SETTINGS                136
#define IDD_IMAGE_SEARCH            137

#define IDC_BTN_ADDFOLDER           1000
#define IDC_BTN_REMOVEFOLDER        1001
#define IDC_BTN_REFRESH             1002
#define IDC_STATIC_SEARCH           1003
#define IDC_EDIT_SEARCH             1004
#define IDC_STATIC_FILTER           1005
#define IDC_COMBO_FILTER            1006
#define IDC_LIST_VIDEOS             1007
#define IDC_PREVIEW                 1008
#define IDC_STATIC_IMAGE            1009
#define IDC_STATIC_NAME_LBL         1010
#define IDC_STATIC_NAME             1011
#define IDC_STATIC_RATING_LBL       1012
#define IDC_COMBO_RATING            1013
#define IDC_STATIC_TAGS_LBL         1014
#define IDC_EDIT_TAGS               1015
#define IDC_STATIC_MEMO_LBL         1016
#define IDC_EDIT_MEMO               1017
#define IDC_BTN_SAVE                1018
#define IDC_BTN_RENAME              1021
#define IDC_BTN_DELETE              1022
#define IDC_BTN_EXPLORER            1023
#define IDC_BTN_OPENDEFAULT         1024
#define IDC_STATIC_STATUS           1025
#define IDC_STATIC_ACTORS_LBL       1026
#define IDC_EDIT_ACTORS             1027
#define IDC_STATIC_STUDIO_LBL       1028
#define IDC_EDIT_STUDIO             1029
#define IDC_RADIO_VIDEO             1030
#define IDC_RADIO_ACTOR             1031
#define IDC_RADIO_STUDIO            1032
#define IDC_RADIO_TAG               1033
#define IDC_LIST_CATEGORY           1034
#define IDC_RADIO_LISTVIEW          1035
#define IDC_RADIO_GRIDVIEW          1036
#define IDC_STATIC_VIEW             1037
#define IDC_STATIC_RELEASE_LBL      1038
#define IDC_DATE_RELEASE            1039
#define IDC_BTN_ACTORS              1040
#define IDC_BTN_PICKACTORS          1041
#define IDC_GRID                    1042
#define IDC_ACTOR_GRID              1043
#define IDC_BTN_ACTOR_BACK          1044
#define IDC_STATIC_ACTOR_TITLE      1045
#define ID_ACTOR_SHOWVIDEOS         32800
#define ID_ACTOR_EDIT               32801
#define ID_CAT_DELETE               32813
#define ID_ACTOR_DELETE             32814
#define ID_VIDEO_TEXTINFO           32815
#define ID_ACTOR_TEXTINFO           32816
#define ID_MANAGE_ACTORS            32810
#define ID_MANAGE_STUDIOS           32811
#define ID_MANAGE_TAGS              32812
#define IDC_BTN_PICKSTUDIO          1046
#define IDC_BTN_PICKTAGS            1047
#define IDC_STATIC_VALIASES_LBL     1156
#define IDC_EDIT_VALIASES           1157
#define IDC_BTN_PICKVALIASES        1158
#define IDC_CAT_GRID                1048
#define IDC_STATIC_TITLE_LBL        1049
#define IDC_EDIT_TITLE              1050
#define IDC_STATIC_SORT             1051
#define IDC_COMBO_SORT              1052
#define IDC_BTN_SORTDIR             1053
#define IDC_BTN_OPENDB              1054
#define IDC_BTN_APPLYDB             1205
#define IDC_BTN_RESCAN              1206
#define IDC_BTN_EXPORTTXT           1207
#define IDC_STATIC_CODE_LBL         1208
#define IDC_EDIT_CODE               1209

// 스튜디오 / 태그 관리 창
#define IDC_NL_SEARCH               1140
#define IDC_NL_LIST                 1141
#define IDC_NL_IMAGE                1142
#define IDC_NL_IMG_BROWSE           1143
#define IDC_NL_IMG_CLEAR            1144
#define IDC_NL_IMAGE_PATH           1145
#define IDC_NL_NAME                 1146
#define IDC_NL_COUNT                1147
#define IDC_NL_MEMO                 1148
#define IDC_NL_NEW                  1149
#define IDC_NL_DELETE               1150
#define IDC_NL_SAVE                 1151
#define IDC_NL_NAME_LBL             1152
#define IDC_NL_COUNT_LBL            1153
#define IDC_NL_MEMO_LBL             1154
#define IDC_NL_BULK                 1201
#define IDC_BN_TEXT                 1196
#define IDC_BN_LIST                 1197
#define IDC_BN_SUMMARY              1198
#define IDC_BN_FAV                  1199
#define IDC_BN_GUIDE                1200
#define IDC_PICK_NEWLABEL           1125
#define IDC_INPUT_PROMPT            1130
#define IDC_INPUT_EDIT              1131

// 배우 관리 창
#define IDC_ACT_SEARCH              1100
#define IDC_ACT_LIST                1101
#define IDC_ACT_PHOTO               1102
#define IDC_ACT_NAME                1103
#define IDC_ACT_ALIASES             1104
#define IDC_ACT_ALIAS_ADD           1160
#define IDC_ACT_ALIAS_DEL           1161
#define IDC_ACT_ALIAS_UP            1162
#define IDC_ACT_ALIAS_DOWN          1163
#define IDC_ACT_BIRTH               1105
#define IDC_ACT_COUNT               1106
#define IDC_ACT_PHOTO_BROWSE        1107
#define IDC_ACT_PHOTO_CLEAR         1108
#define IDC_ACT_PHOTO_PATH          1109
#define IDC_ACT_MEMO                1110
#define IDC_ACT_NEW                 1111
#define IDC_ACT_DELETE              1112
#define IDC_ACT_SAVE                1113
#define IDC_ACT_AGE                 1114
#define IDC_ACT_NATIONALITY         1115
#define IDC_ACT_HEIGHT              1116
#define IDC_ACT_DEBUT               1117
#define IDC_ACT_RETIRE              1164
#define IDC_ACT_RATING              1168
#define IDC_ACTOR_RATING            1169
#define IDC_ACTOR_RATING_LBL        1170
#define IDC_BTN_SETTINGS            1171
#define IDC_ACTOR_FAV               1172
#define IDC_ACTOR_PANEL             1173
#define IDC_ACTOR_STRIP             1202
#define IDC_MEDIA_INFO              1203
#define IDC_DROP_COUNTER            1204
#define IDC_ACT_BUST                1174
#define IDC_ACT_WAIST               1175
#define IDC_ACT_HIP                 1176
#define IDC_ACT_CUP                 1177
#define IDC_SET_DEL_VIDEO           1178
#define IDC_SET_DEL_ACTOR           1179
#define IDC_SET_DEL_STUDIO          1180
#define IDC_SET_DEL_TAG             1181
#define IDC_SET_DEL_BTN             1182
#define IDC_IMGS_QUERY              1183
#define IDC_IMGS_SEARCH             1184
#define IDC_IMGS_GRID               1185
#define IDC_IMGS_STATUS             1186
#define IDC_ACT_PHOTO_SEARCH        1187
#define IDC_SET_GAPI_KEY            1188
#define IDC_SET_GAPI_CX             1189
#define IDC_IMGS_ENGINE             1190
#define IDC_IMGS_SAFEOFF            1191
#define IDC_IMGS_PREV               1192
#define IDC_IMGS_NEXT               1193
#define IDC_BTN_CHANGEIMAGE         1194
#define IDC_BTN_SEARCHIMAGE         1195
#define IDC_TAG_CHIPS               1165
#define IDC_ZOOM_SLIDER             1166
#define IDC_ACTOR_CHIPS             1167
#define IDC_STUDIO_CHIPS            1210
#define IDC_TI_TEXT                 1211
#define IDC_TI_GUIDE                1212
#define IDC_ACT_URLS                1213
#define IDC_NL_SUB_LBL              1214
#define IDC_NL_SUB                  1215
#define IDC_ACT_GENDER              1159

// 배우 선택 창
#define IDC_PICK_SEARCH             1120
#define IDC_PICK_LIST               1121
#define IDC_PICK_NEWNAME            1122
#define IDC_PICK_ADD                1123
#define IDC_PICK_SELECTED           1124

// 다음은 새 개체에 사용할 기본값입니다.
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE    140
#define _APS_NEXT_COMMAND_VALUE     32817
#define _APS_NEXT_CONTROL_VALUE     1216
#define _APS_NEXT_SYMED_VALUE       101
#endif
#endif
